### ISSUE TITLE
Unable to run locally

### ISSUE THREAD

**Issue by ThePsionic** [unlucky4ever/RuneCord#2]
When trying to run locally per the steps in the README, the following error is thrown:
```text
module.js:327
    throw err;
    ^

Error: Cannot find module '../db/servers.json'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Tom\Documents\Code\RuneCord\bot\db.js:3:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```
The file (and even the folder) in question indeed don't exist; I assume they are to be generated on first run, but it is somehow skipped.

**Comment by unlucky4ever** [comment]
You must create a folder called `db` and inside that folder create 2 files `servers.json` and `times.json` each one with an initial content of `{}`

I will update the README with this right now.
